version: 2

references:

  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip
  
  arch_deps: &arch_deps
    run:
      name: Install dependencies on Arch Linux.
      command: |
        pacman -S --noconfirm python python-pip git base-devel
  
  install: &install
    run:
      name: Install.
      command: |
        pip3 install tensorflow
        pip3 install .

  test: &test
    run:
      name: Run tests.
      command: |
        python3 setup.py test
  
jobs:
            
  test_ubuntu16.04:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/cxflow-tensorflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_ubuntu16.10:
    docker:
      - image: ubuntu:16.10
    working_directory: ~/cxflow-tensorflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_ubuntu17.04:
    docker:
      - image: ubuntu:17.04
    working_directory: ~/cxflow-tensorflow
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_archlinux:
    docker:
      - image: pritunl/archlinux:2017-07-08
    working_directory: ~/cxflow-tensorflow
    steps:
      - *arch_deps
      - checkout
      - *install
      - *test

workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu16.04
      - test_ubuntu16.10
      - test_ubuntu17.04
      - test_archlinux
